- hosts: default
  sudo: yes
  tasks:
    - name: Change mirror server
      shell: sed -i".bak" 's#http://us.archive.ubuntu.com/ubuntu#http://ftp.jaist.ac.jp/pub/Linux/ubuntu#' /etc/apt/sources.list
    - name: apt update
      apt: update_cache=yes
  
